version: "3"

services:
  fuxa:
    image: frangoteam/fuxa:latest
    container_name: fuxa
    ports:
      - 1881:1881
    restart: unless-stopped
    volumes:
      - /home/pi/scada-system/DockerServer/folders/fuxa/appdata:/usr/src/app/FUXA/server/_appdata:rw
      - /home/pi/scada-system/DockerServer/folders/fuxa/db:/usr/src/app/FUXA/server/_db:rw
      - /home/pi/scada-system/DockerServer/folders/fuxa/logs:/usr/src/app/FUXA/server/_logs:rw
      - /home/pi/scada-system/DockerServer/folders/fuxa/images:/usr/src/app/FUXA/server/_images:rw
    depends_on:
      - influxdb

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - /home/pi/scada-system/DockerServer/folders/mosquitto/config:/mosquitto/config:rw
      - /home/pi/scada-system/DockerServer/folders/mosquitto/data:/mosquitto/data:rw
      - /home/pi/scada-system/DockerServer/folders/mosquitto/log:/mosquitto/log:rw

    ports:
      - 1883:1883
      - 9001:9001
    restart: always

  influxdb:
    image: influxdb:latest
    container_name: influxdb2
    volumes:
      - /home/pi/scada-system/DockerServer/folders/influxdb/data:/var/lib/influxdb2:rw

    ports:
      - 8086:8086
    restart: unless-stopped

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - 3005:8888
    volumes:
      - /home/pi/scada-system/DockerServer/folders/chronograf/data:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - INFLUXDB_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - INFLUXDB_ORG=${DOCKER_INFLUXDB_INIT_ORG}
    restart: unless-stopped

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - 3000:3000
  #   user: "0"
  #   volumes:
  #     - /home/pi/scada-system/DockerServer/folders/grafana/data:/var/lib/grafana
  #     - /home/pi/scada-system/DockerServer/folders/grafana/grafana-provisioning:/etc/grafana/provisioning
  #   depends_on:
  #     - influxdb
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=${DOCKER_INFLUXDB_INIT_USERNAME}
  #     - GF_SECURITY_ADMIN_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
  #   restart: unless-stopped

  # telegraf:
  #   image: telegraf:latest
  #   container_name: telegraf
  #   #    links:
  #   #      - influxdb
  #   volumes:
  #     #  Map Telegraf configuration file
  #     - /home/pi/scada-system/DockerServer/folders/influxdb/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  #     #  Map /tmp to permanent storage  (this includes /tmp/metrics.out)
  #     - /home/pi/scada-system/DockerServer/folders/influxdb:/tmp:rw
  #   restart: unless-stopped
  #   depends_on:
  #     - influxdb
  #   links:
  #     - influxdb

  solarcontroller:
    image: bleialf/solarcontroller:latest
    container_name: solarcontroller
    restart: unless-stopped
    depends_on:
      - mosquitto

  # influxdb_cleaner:
  #   image: bleialf/influxdb_cleaner:latest
  #   container_name: influxdb_cleaner
  #   restart: unless-stopped
  #   environment:
  #     - INFLUXDB_URL=http://influxdb:8086
  #     - INFLUXDB_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
  #     - INFLUXDB_ORG=${DOCKER_INFLUXDB_INIT_ORG}
  #   depends_on:
  #     - influxdb
  dokuserver:
    image: bleialf/dokuserver:latest
    container_name: dokuserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /home/pi/scada-system/DokuServer/templates:/templates:ro
      - /home/pi/scada-system/DokuServer/firmware:/firmware:ro
  piwpcontroller:
    image: bleialf/piwpcontroller
    container_name: wpcontroller
    restart: unless-stopped
    volumes:
      - /dev/ttyAMA1:/dev/ttyAMA1
